# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: A computer's logbook
email: dansando@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the blog and personal web page of Daniel Sanchez Dominguez (daneelsan,
   dansando, daniels). It's mainly packed with stuff about computers,
   programming, and all sorts of random things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daneelsan.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: daneelsan
github_username:  daneelsan
wolfram_community_username:  daniels

# Build settings
markdown: kramdown
highlighter: rouge
